baseURL: "https://www.theomorales.com/" 
title: Théo Morales
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Tags
          url: /tags/
          weight: 2     
        - name: Blog
          url: https://notes.theomorales.com
          weight: 3

params:
    description: "PhD student at Trinity College Dublin researching hand-object interaction in manipulation sequences and images."
    author: Théo Morales
    #googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Théo Morales
          subtitle: "I am a PhD student in the School of Computer Science and Statistics at Trinity College Dublin. My research is on novel Computer Vision & Deep Learning methods for accurate hand-object interaction tracking. I am mostly interested in Test-Time Adaptation (TTA), representation learning, meta-learning and hand-object interaction fields."
          imageUrl: "/me_pretty.png"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Théo Morales
          buttons:
            - name: Papers
              url: /papers/
            - name: Blog
              url: https://notes.theomorales.com
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: https://mailhide.io/e/XLb3qiRc
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=S0hZCVEAAAAJ
        - name: Research Gate
          url: https://www.researchgate.net/profile/Theo-Morales
        - name: YouTube
          url: https://www.youtube.com/@theomorales5040
        - name: GitHub
          url: https://github.com/DubiousCactus

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Théo Morales"
      icon: /favicon.png
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
